name: verify attribution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-attribution:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build attribution-gen
      run: make build

    - name: Run attribution-gen
      run: ./bin/attribution-gen --output generated_attribution.md

    - name: Compare ATTRIBUTION.md files
      run: |
        if cmp -s ATTRIBUTION.md generated_attribution.md; then
          echo "ATTRIBUTION.md is up to date"
        else
          echo "ATTRIBUTION.md is not up to date. Please regenerate it."
          exit 1
        fi

    - name: Clean up
      if: always()
      run: rm -f attribution-gen generated_attribution.md